// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main_proto.proto

package pengcui.protoBuf;

public final class bufClass {
  private bufClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pengcui.protoBuf.Buf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 operateType = 1;</code>
     */
    int getOperateType();

    /**
     * <pre>
     *0.输入法
     * </pre>
     *
     * <code>optional bool isDel = 22;</code>
     */
    boolean getIsDel();

    /**
     * <code>optional string InputText = 2;</code>
     */
    java.lang.String getInputText();
    /**
     * <code>optional string InputText = 2;</code>
     */
    com.google.protobuf.ByteString
        getInputTextBytes();

    /**
     * <pre>
     *1.gps
     * </pre>
     *
     * <code>optional int32 gpsStart = 3;</code>
     */
    int getGpsStart();

    /**
     * <code>optional double longitude = 4;</code>
     */
    double getLongitude();

    /**
     * <code>optional double latitude = 5;</code>
     */
    double getLatitude();

    /**
     * <code>optional double altitude = 6;</code>
     */
    double getAltitude();

    /**
     * <code>optional int64 delay = 15;</code>
     */
    long getDelay();

    /**
     * <pre>
     *3.打开网页
     * </pre>
     *
     * <code>optional string url = 9;</code>
     */
    java.lang.String getUrl();
    /**
     * <pre>
     *3.打开网页
     * </pre>
     *
     * <code>optional string url = 9;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     *4.物理按键
     * </pre>
     *
     * <code>optional int32 keyCode = 10;</code>
     */
    int getKeyCode();

    /**
     * <pre>
     *5.查找元素位置
     * </pre>
     *
     * <code>optional int32 findOf = 11;</code>
     */
    int getFindOf();

    /**
     * <code>optional string findStr = 12;</code>
     */
    java.lang.String getFindStr();
    /**
     * <code>optional string findStr = 12;</code>
     */
    com.google.protobuf.ByteString
        getFindStrBytes();

    /**
     * <code>optional bool isChild = 24;</code>
     */
    boolean getIsChild();

    /**
     * <code>optional string childStr = 25;</code>
     */
    java.lang.String getChildStr();
    /**
     * <code>optional string childStr = 25;</code>
     */
    com.google.protobuf.ByteString
        getChildStrBytes();

    /**
     * <code>optional int32 childLayer = 26;</code>
     */
    int getChildLayer();

    /**
     * <pre>
     *6.执行命令 
     * </pre>
     *
     * <code>optional string cmdStr = 13;</code>
     */
    java.lang.String getCmdStr();
    /**
     * <pre>
     *6.执行命令 
     * </pre>
     *
     * <code>optional string cmdStr = 13;</code>
     */
    com.google.protobuf.ByteString
        getCmdStrBytes();

    /**
     * <code>optional bool isRoot = 14;</code>
     */
    boolean getIsRoot();

    /**
     * <pre>
     *7.添加联系人
     * </pre>
     *
     * <code>optional int32 contactType = 23;</code>
     */
    int getContactType();

    /**
     * <code>optional string contactName = 16;</code>
     */
    java.lang.String getContactName();
    /**
     * <code>optional string contactName = 16;</code>
     */
    com.google.protobuf.ByteString
        getContactNameBytes();

    /**
     * <code>optional string contactNum = 17;</code>
     */
    java.lang.String getContactNum();
    /**
     * <code>optional string contactNum = 17;</code>
     */
    com.google.protobuf.ByteString
        getContactNumBytes();

    /**
     * <code>optional int32 contactCount = 19;</code>
     */
    int getContactCount();

    /**
     * <pre>
     *9.上传文件
     * </pre>
     *
     * <code>optional string fileName = 20;</code>
     */
    java.lang.String getFileName();
    /**
     * <pre>
     *9.上传文件
     * </pre>
     *
     * <code>optional string fileName = 20;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional int32 fileLen = 21;</code>
     */
    int getFileLen();

    /**
     * <pre>
     *10.设置微信自动回复的开始或暂停，默认暂停
     * </pre>
     *
     * <code>optional bool wxRun = 29;</code>
     */
    boolean getWxRun();

    /**
     * <pre>
     *12.设置屏幕广告
     * </pre>
     *
     * <code>optional string gText = 27;</code>
     */
    java.lang.String getGText();
    /**
     * <pre>
     *12.设置屏幕广告
     * </pre>
     *
     * <code>optional string gText = 27;</code>
     */
    com.google.protobuf.ByteString
        getGTextBytes();

    /**
     * <code>optional bool gView = 28;</code>
     */
    boolean getGView();

    /**
     * <pre>
     *15.设置聊天机器人api的key和userId
     * </pre>
     *
     * <code>optional string robotApiKey = 30;</code>
     */
    java.lang.String getRobotApiKey();
    /**
     * <pre>
     *15.设置聊天机器人api的key和userId
     * </pre>
     *
     * <code>optional string robotApiKey = 30;</code>
     */
    com.google.protobuf.ByteString
        getRobotApiKeyBytes();

    /**
     * <pre>
     *17.从手机给电脑下载文件
     * </pre>
     *
     * <code>optional string dlUrl = 31;</code>
     */
    java.lang.String getDlUrl();
    /**
     * <pre>
     *17.从手机给电脑下载文件
     * </pre>
     *
     * <code>optional string dlUrl = 31;</code>
     */
    com.google.protobuf.ByteString
        getDlUrlBytes();
  }
  /**
   * Protobuf type {@code pengcui.protoBuf.Buf}
   */
  public  static final class Buf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pengcui.protoBuf.Buf)
      BufOrBuilder {
    // Use Buf.newBuilder() to construct.
    private Buf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Buf() {
      operateType_ = 0;
      isDel_ = false;
      inputText_ = "";
      gpsStart_ = 0;
      longitude_ = 0D;
      latitude_ = 0D;
      altitude_ = 0D;
      delay_ = 0L;
      url_ = "";
      keyCode_ = 0;
      findOf_ = 0;
      findStr_ = "";
      isChild_ = false;
      childStr_ = "";
      childLayer_ = 0;
      cmdStr_ = "";
      isRoot_ = false;
      contactType_ = 0;
      contactName_ = "";
      contactNum_ = "";
      contactCount_ = 0;
      fileName_ = "";
      fileLen_ = 0;
      wxRun_ = false;
      gText_ = "";
      gView_ = false;
      robotApiKey_ = "";
      dlUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Buf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              operateType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              inputText_ = s;
              break;
            }
            case 24: {

              gpsStart_ = input.readInt32();
              break;
            }
            case 33: {

              longitude_ = input.readDouble();
              break;
            }
            case 41: {

              latitude_ = input.readDouble();
              break;
            }
            case 49: {

              altitude_ = input.readDouble();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 80: {

              keyCode_ = input.readInt32();
              break;
            }
            case 88: {

              findOf_ = input.readInt32();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              findStr_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              cmdStr_ = s;
              break;
            }
            case 112: {

              isRoot_ = input.readBool();
              break;
            }
            case 120: {

              delay_ = input.readInt64();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              contactName_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              contactNum_ = s;
              break;
            }
            case 152: {

              contactCount_ = input.readInt32();
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 168: {

              fileLen_ = input.readInt32();
              break;
            }
            case 176: {

              isDel_ = input.readBool();
              break;
            }
            case 184: {

              contactType_ = input.readInt32();
              break;
            }
            case 192: {

              isChild_ = input.readBool();
              break;
            }
            case 202: {
              java.lang.String s = input.readStringRequireUtf8();

              childStr_ = s;
              break;
            }
            case 208: {

              childLayer_ = input.readInt32();
              break;
            }
            case 218: {
              java.lang.String s = input.readStringRequireUtf8();

              gText_ = s;
              break;
            }
            case 224: {

              gView_ = input.readBool();
              break;
            }
            case 232: {

              wxRun_ = input.readBool();
              break;
            }
            case 242: {
              java.lang.String s = input.readStringRequireUtf8();

              robotApiKey_ = s;
              break;
            }
            case 250: {
              java.lang.String s = input.readStringRequireUtf8();

              dlUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pengcui.protoBuf.bufClass.internal_static_pengcui_protoBuf_Buf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pengcui.protoBuf.bufClass.internal_static_pengcui_protoBuf_Buf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pengcui.protoBuf.bufClass.Buf.class, pengcui.protoBuf.bufClass.Buf.Builder.class);
    }

    public static final int OPERATETYPE_FIELD_NUMBER = 1;
    private int operateType_;
    /**
     * <code>optional int32 operateType = 1;</code>
     */
    public int getOperateType() {
      return operateType_;
    }

    public static final int ISDEL_FIELD_NUMBER = 22;
    private boolean isDel_;
    /**
     * <pre>
     *0.输入法
     * </pre>
     *
     * <code>optional bool isDel = 22;</code>
     */
    public boolean getIsDel() {
      return isDel_;
    }

    public static final int INPUTTEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object inputText_;
    /**
     * <code>optional string InputText = 2;</code>
     */
    public java.lang.String getInputText() {
      java.lang.Object ref = inputText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inputText_ = s;
        return s;
      }
    }
    /**
     * <code>optional string InputText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInputTextBytes() {
      java.lang.Object ref = inputText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GPSSTART_FIELD_NUMBER = 3;
    private int gpsStart_;
    /**
     * <pre>
     *1.gps
     * </pre>
     *
     * <code>optional int32 gpsStart = 3;</code>
     */
    public int getGpsStart() {
      return gpsStart_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    /**
     * <code>optional double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 5;
    private double latitude_;
    /**
     * <code>optional double latitude = 5;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 6;
    private double altitude_;
    /**
     * <code>optional double altitude = 6;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    public static final int DELAY_FIELD_NUMBER = 15;
    private long delay_;
    /**
     * <code>optional int64 delay = 15;</code>
     */
    public long getDelay() {
      return delay_;
    }

    public static final int URL_FIELD_NUMBER = 9;
    private volatile java.lang.Object url_;
    /**
     * <pre>
     *3.打开网页
     * </pre>
     *
     * <code>optional string url = 9;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *3.打开网页
     * </pre>
     *
     * <code>optional string url = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYCODE_FIELD_NUMBER = 10;
    private int keyCode_;
    /**
     * <pre>
     *4.物理按键
     * </pre>
     *
     * <code>optional int32 keyCode = 10;</code>
     */
    public int getKeyCode() {
      return keyCode_;
    }

    public static final int FINDOF_FIELD_NUMBER = 11;
    private int findOf_;
    /**
     * <pre>
     *5.查找元素位置
     * </pre>
     *
     * <code>optional int32 findOf = 11;</code>
     */
    public int getFindOf() {
      return findOf_;
    }

    public static final int FINDSTR_FIELD_NUMBER = 12;
    private volatile java.lang.Object findStr_;
    /**
     * <code>optional string findStr = 12;</code>
     */
    public java.lang.String getFindStr() {
      java.lang.Object ref = findStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        findStr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string findStr = 12;</code>
     */
    public com.google.protobuf.ByteString
        getFindStrBytes() {
      java.lang.Object ref = findStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        findStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISCHILD_FIELD_NUMBER = 24;
    private boolean isChild_;
    /**
     * <code>optional bool isChild = 24;</code>
     */
    public boolean getIsChild() {
      return isChild_;
    }

    public static final int CHILDSTR_FIELD_NUMBER = 25;
    private volatile java.lang.Object childStr_;
    /**
     * <code>optional string childStr = 25;</code>
     */
    public java.lang.String getChildStr() {
      java.lang.Object ref = childStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        childStr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string childStr = 25;</code>
     */
    public com.google.protobuf.ByteString
        getChildStrBytes() {
      java.lang.Object ref = childStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        childStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDLAYER_FIELD_NUMBER = 26;
    private int childLayer_;
    /**
     * <code>optional int32 childLayer = 26;</code>
     */
    public int getChildLayer() {
      return childLayer_;
    }

    public static final int CMDSTR_FIELD_NUMBER = 13;
    private volatile java.lang.Object cmdStr_;
    /**
     * <pre>
     *6.执行命令 
     * </pre>
     *
     * <code>optional string cmdStr = 13;</code>
     */
    public java.lang.String getCmdStr() {
      java.lang.Object ref = cmdStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmdStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *6.执行命令 
     * </pre>
     *
     * <code>optional string cmdStr = 13;</code>
     */
    public com.google.protobuf.ByteString
        getCmdStrBytes() {
      java.lang.Object ref = cmdStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISROOT_FIELD_NUMBER = 14;
    private boolean isRoot_;
    /**
     * <code>optional bool isRoot = 14;</code>
     */
    public boolean getIsRoot() {
      return isRoot_;
    }

    public static final int CONTACTTYPE_FIELD_NUMBER = 23;
    private int contactType_;
    /**
     * <pre>
     *7.添加联系人
     * </pre>
     *
     * <code>optional int32 contactType = 23;</code>
     */
    public int getContactType() {
      return contactType_;
    }

    public static final int CONTACTNAME_FIELD_NUMBER = 16;
    private volatile java.lang.Object contactName_;
    /**
     * <code>optional string contactName = 16;</code>
     */
    public java.lang.String getContactName() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contactName = 16;</code>
     */
    public com.google.protobuf.ByteString
        getContactNameBytes() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACTNUM_FIELD_NUMBER = 17;
    private volatile java.lang.Object contactNum_;
    /**
     * <code>optional string contactNum = 17;</code>
     */
    public java.lang.String getContactNum() {
      java.lang.Object ref = contactNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactNum_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contactNum = 17;</code>
     */
    public com.google.protobuf.ByteString
        getContactNumBytes() {
      java.lang.Object ref = contactNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACTCOUNT_FIELD_NUMBER = 19;
    private int contactCount_;
    /**
     * <code>optional int32 contactCount = 19;</code>
     */
    public int getContactCount() {
      return contactCount_;
    }

    public static final int FILENAME_FIELD_NUMBER = 20;
    private volatile java.lang.Object fileName_;
    /**
     * <pre>
     *9.上传文件
     * </pre>
     *
     * <code>optional string fileName = 20;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *9.上传文件
     * </pre>
     *
     * <code>optional string fileName = 20;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILELEN_FIELD_NUMBER = 21;
    private int fileLen_;
    /**
     * <code>optional int32 fileLen = 21;</code>
     */
    public int getFileLen() {
      return fileLen_;
    }

    public static final int WXRUN_FIELD_NUMBER = 29;
    private boolean wxRun_;
    /**
     * <pre>
     *10.设置微信自动回复的开始或暂停，默认暂停
     * </pre>
     *
     * <code>optional bool wxRun = 29;</code>
     */
    public boolean getWxRun() {
      return wxRun_;
    }

    public static final int GTEXT_FIELD_NUMBER = 27;
    private volatile java.lang.Object gText_;
    /**
     * <pre>
     *12.设置屏幕广告
     * </pre>
     *
     * <code>optional string gText = 27;</code>
     */
    public java.lang.String getGText() {
      java.lang.Object ref = gText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gText_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *12.设置屏幕广告
     * </pre>
     *
     * <code>optional string gText = 27;</code>
     */
    public com.google.protobuf.ByteString
        getGTextBytes() {
      java.lang.Object ref = gText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GVIEW_FIELD_NUMBER = 28;
    private boolean gView_;
    /**
     * <code>optional bool gView = 28;</code>
     */
    public boolean getGView() {
      return gView_;
    }

    public static final int ROBOTAPIKEY_FIELD_NUMBER = 30;
    private volatile java.lang.Object robotApiKey_;
    /**
     * <pre>
     *15.设置聊天机器人api的key和userId
     * </pre>
     *
     * <code>optional string robotApiKey = 30;</code>
     */
    public java.lang.String getRobotApiKey() {
      java.lang.Object ref = robotApiKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        robotApiKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *15.设置聊天机器人api的key和userId
     * </pre>
     *
     * <code>optional string robotApiKey = 30;</code>
     */
    public com.google.protobuf.ByteString
        getRobotApiKeyBytes() {
      java.lang.Object ref = robotApiKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        robotApiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DLURL_FIELD_NUMBER = 31;
    private volatile java.lang.Object dlUrl_;
    /**
     * <pre>
     *17.从手机给电脑下载文件
     * </pre>
     *
     * <code>optional string dlUrl = 31;</code>
     */
    public java.lang.String getDlUrl() {
      java.lang.Object ref = dlUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dlUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *17.从手机给电脑下载文件
     * </pre>
     *
     * <code>optional string dlUrl = 31;</code>
     */
    public com.google.protobuf.ByteString
        getDlUrlBytes() {
      java.lang.Object ref = dlUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dlUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operateType_ != 0) {
        output.writeInt32(1, operateType_);
      }
      if (!getInputTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, inputText_);
      }
      if (gpsStart_ != 0) {
        output.writeInt32(3, gpsStart_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(4, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(5, latitude_);
      }
      if (altitude_ != 0D) {
        output.writeDouble(6, altitude_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, url_);
      }
      if (keyCode_ != 0) {
        output.writeInt32(10, keyCode_);
      }
      if (findOf_ != 0) {
        output.writeInt32(11, findOf_);
      }
      if (!getFindStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, findStr_);
      }
      if (!getCmdStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, cmdStr_);
      }
      if (isRoot_ != false) {
        output.writeBool(14, isRoot_);
      }
      if (delay_ != 0L) {
        output.writeInt64(15, delay_);
      }
      if (!getContactNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, contactName_);
      }
      if (!getContactNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, contactNum_);
      }
      if (contactCount_ != 0) {
        output.writeInt32(19, contactCount_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, fileName_);
      }
      if (fileLen_ != 0) {
        output.writeInt32(21, fileLen_);
      }
      if (isDel_ != false) {
        output.writeBool(22, isDel_);
      }
      if (contactType_ != 0) {
        output.writeInt32(23, contactType_);
      }
      if (isChild_ != false) {
        output.writeBool(24, isChild_);
      }
      if (!getChildStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 25, childStr_);
      }
      if (childLayer_ != 0) {
        output.writeInt32(26, childLayer_);
      }
      if (!getGTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 27, gText_);
      }
      if (gView_ != false) {
        output.writeBool(28, gView_);
      }
      if (wxRun_ != false) {
        output.writeBool(29, wxRun_);
      }
      if (!getRobotApiKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 30, robotApiKey_);
      }
      if (!getDlUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 31, dlUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operateType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operateType_);
      }
      if (!getInputTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, inputText_);
      }
      if (gpsStart_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gpsStart_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, latitude_);
      }
      if (altitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, altitude_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, url_);
      }
      if (keyCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, keyCode_);
      }
      if (findOf_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, findOf_);
      }
      if (!getFindStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, findStr_);
      }
      if (!getCmdStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, cmdStr_);
      }
      if (isRoot_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, isRoot_);
      }
      if (delay_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, delay_);
      }
      if (!getContactNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, contactName_);
      }
      if (!getContactNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, contactNum_);
      }
      if (contactCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, contactCount_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, fileName_);
      }
      if (fileLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, fileLen_);
      }
      if (isDel_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(22, isDel_);
      }
      if (contactType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, contactType_);
      }
      if (isChild_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(24, isChild_);
      }
      if (!getChildStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(25, childStr_);
      }
      if (childLayer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(26, childLayer_);
      }
      if (!getGTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(27, gText_);
      }
      if (gView_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(28, gView_);
      }
      if (wxRun_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(29, wxRun_);
      }
      if (!getRobotApiKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(30, robotApiKey_);
      }
      if (!getDlUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(31, dlUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pengcui.protoBuf.bufClass.Buf)) {
        return super.equals(obj);
      }
      pengcui.protoBuf.bufClass.Buf other = (pengcui.protoBuf.bufClass.Buf) obj;

      boolean result = true;
      result = result && (getOperateType()
          == other.getOperateType());
      result = result && (getIsDel()
          == other.getIsDel());
      result = result && getInputText()
          .equals(other.getInputText());
      result = result && (getGpsStart()
          == other.getGpsStart());
      result = result && (
          java.lang.Double.doubleToLongBits(getLongitude())
          == java.lang.Double.doubleToLongBits(
              other.getLongitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLatitude())
          == java.lang.Double.doubleToLongBits(
              other.getLatitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getAltitude())
          == java.lang.Double.doubleToLongBits(
              other.getAltitude()));
      result = result && (getDelay()
          == other.getDelay());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && (getKeyCode()
          == other.getKeyCode());
      result = result && (getFindOf()
          == other.getFindOf());
      result = result && getFindStr()
          .equals(other.getFindStr());
      result = result && (getIsChild()
          == other.getIsChild());
      result = result && getChildStr()
          .equals(other.getChildStr());
      result = result && (getChildLayer()
          == other.getChildLayer());
      result = result && getCmdStr()
          .equals(other.getCmdStr());
      result = result && (getIsRoot()
          == other.getIsRoot());
      result = result && (getContactType()
          == other.getContactType());
      result = result && getContactName()
          .equals(other.getContactName());
      result = result && getContactNum()
          .equals(other.getContactNum());
      result = result && (getContactCount()
          == other.getContactCount());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getFileLen()
          == other.getFileLen());
      result = result && (getWxRun()
          == other.getWxRun());
      result = result && getGText()
          .equals(other.getGText());
      result = result && (getGView()
          == other.getGView());
      result = result && getRobotApiKey()
          .equals(other.getRobotApiKey());
      result = result && getDlUrl()
          .equals(other.getDlUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OPERATETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOperateType();
      hash = (37 * hash) + ISDEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDel());
      hash = (37 * hash) + INPUTTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getInputText().hashCode();
      hash = (37 * hash) + GPSSTART_FIELD_NUMBER;
      hash = (53 * hash) + getGpsStart();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAltitude()));
      hash = (37 * hash) + DELAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDelay());
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + KEYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getKeyCode();
      hash = (37 * hash) + FINDOF_FIELD_NUMBER;
      hash = (53 * hash) + getFindOf();
      hash = (37 * hash) + FINDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getFindStr().hashCode();
      hash = (37 * hash) + ISCHILD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsChild());
      hash = (37 * hash) + CHILDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getChildStr().hashCode();
      hash = (37 * hash) + CHILDLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getChildLayer();
      hash = (37 * hash) + CMDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getCmdStr().hashCode();
      hash = (37 * hash) + ISROOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRoot());
      hash = (37 * hash) + CONTACTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContactType();
      hash = (37 * hash) + CONTACTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getContactName().hashCode();
      hash = (37 * hash) + CONTACTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getContactNum().hashCode();
      hash = (37 * hash) + CONTACTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getContactCount();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILELEN_FIELD_NUMBER;
      hash = (53 * hash) + getFileLen();
      hash = (37 * hash) + WXRUN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWxRun());
      hash = (37 * hash) + GTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getGText().hashCode();
      hash = (37 * hash) + GVIEW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGView());
      hash = (37 * hash) + ROBOTAPIKEY_FIELD_NUMBER;
      hash = (53 * hash) + getRobotApiKey().hashCode();
      hash = (37 * hash) + DLURL_FIELD_NUMBER;
      hash = (53 * hash) + getDlUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pengcui.protoBuf.bufClass.Buf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pengcui.protoBuf.bufClass.Buf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pengcui.protoBuf.bufClass.Buf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pengcui.protoBuf.bufClass.Buf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pengcui.protoBuf.Buf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pengcui.protoBuf.Buf)
        pengcui.protoBuf.bufClass.BufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pengcui.protoBuf.bufClass.internal_static_pengcui_protoBuf_Buf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pengcui.protoBuf.bufClass.internal_static_pengcui_protoBuf_Buf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pengcui.protoBuf.bufClass.Buf.class, pengcui.protoBuf.bufClass.Buf.Builder.class);
      }

      // Construct using pengcui.protoBuf.bufClass.Buf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operateType_ = 0;

        isDel_ = false;

        inputText_ = "";

        gpsStart_ = 0;

        longitude_ = 0D;

        latitude_ = 0D;

        altitude_ = 0D;

        delay_ = 0L;

        url_ = "";

        keyCode_ = 0;

        findOf_ = 0;

        findStr_ = "";

        isChild_ = false;

        childStr_ = "";

        childLayer_ = 0;

        cmdStr_ = "";

        isRoot_ = false;

        contactType_ = 0;

        contactName_ = "";

        contactNum_ = "";

        contactCount_ = 0;

        fileName_ = "";

        fileLen_ = 0;

        wxRun_ = false;

        gText_ = "";

        gView_ = false;

        robotApiKey_ = "";

        dlUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pengcui.protoBuf.bufClass.internal_static_pengcui_protoBuf_Buf_descriptor;
      }

      public pengcui.protoBuf.bufClass.Buf getDefaultInstanceForType() {
        return pengcui.protoBuf.bufClass.Buf.getDefaultInstance();
      }

      public pengcui.protoBuf.bufClass.Buf build() {
        pengcui.protoBuf.bufClass.Buf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pengcui.protoBuf.bufClass.Buf buildPartial() {
        pengcui.protoBuf.bufClass.Buf result = new pengcui.protoBuf.bufClass.Buf(this);
        result.operateType_ = operateType_;
        result.isDel_ = isDel_;
        result.inputText_ = inputText_;
        result.gpsStart_ = gpsStart_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        result.altitude_ = altitude_;
        result.delay_ = delay_;
        result.url_ = url_;
        result.keyCode_ = keyCode_;
        result.findOf_ = findOf_;
        result.findStr_ = findStr_;
        result.isChild_ = isChild_;
        result.childStr_ = childStr_;
        result.childLayer_ = childLayer_;
        result.cmdStr_ = cmdStr_;
        result.isRoot_ = isRoot_;
        result.contactType_ = contactType_;
        result.contactName_ = contactName_;
        result.contactNum_ = contactNum_;
        result.contactCount_ = contactCount_;
        result.fileName_ = fileName_;
        result.fileLen_ = fileLen_;
        result.wxRun_ = wxRun_;
        result.gText_ = gText_;
        result.gView_ = gView_;
        result.robotApiKey_ = robotApiKey_;
        result.dlUrl_ = dlUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pengcui.protoBuf.bufClass.Buf) {
          return mergeFrom((pengcui.protoBuf.bufClass.Buf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pengcui.protoBuf.bufClass.Buf other) {
        if (other == pengcui.protoBuf.bufClass.Buf.getDefaultInstance()) return this;
        if (other.getOperateType() != 0) {
          setOperateType(other.getOperateType());
        }
        if (other.getIsDel() != false) {
          setIsDel(other.getIsDel());
        }
        if (!other.getInputText().isEmpty()) {
          inputText_ = other.inputText_;
          onChanged();
        }
        if (other.getGpsStart() != 0) {
          setGpsStart(other.getGpsStart());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getAltitude() != 0D) {
          setAltitude(other.getAltitude());
        }
        if (other.getDelay() != 0L) {
          setDelay(other.getDelay());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getKeyCode() != 0) {
          setKeyCode(other.getKeyCode());
        }
        if (other.getFindOf() != 0) {
          setFindOf(other.getFindOf());
        }
        if (!other.getFindStr().isEmpty()) {
          findStr_ = other.findStr_;
          onChanged();
        }
        if (other.getIsChild() != false) {
          setIsChild(other.getIsChild());
        }
        if (!other.getChildStr().isEmpty()) {
          childStr_ = other.childStr_;
          onChanged();
        }
        if (other.getChildLayer() != 0) {
          setChildLayer(other.getChildLayer());
        }
        if (!other.getCmdStr().isEmpty()) {
          cmdStr_ = other.cmdStr_;
          onChanged();
        }
        if (other.getIsRoot() != false) {
          setIsRoot(other.getIsRoot());
        }
        if (other.getContactType() != 0) {
          setContactType(other.getContactType());
        }
        if (!other.getContactName().isEmpty()) {
          contactName_ = other.contactName_;
          onChanged();
        }
        if (!other.getContactNum().isEmpty()) {
          contactNum_ = other.contactNum_;
          onChanged();
        }
        if (other.getContactCount() != 0) {
          setContactCount(other.getContactCount());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getFileLen() != 0) {
          setFileLen(other.getFileLen());
        }
        if (other.getWxRun() != false) {
          setWxRun(other.getWxRun());
        }
        if (!other.getGText().isEmpty()) {
          gText_ = other.gText_;
          onChanged();
        }
        if (other.getGView() != false) {
          setGView(other.getGView());
        }
        if (!other.getRobotApiKey().isEmpty()) {
          robotApiKey_ = other.robotApiKey_;
          onChanged();
        }
        if (!other.getDlUrl().isEmpty()) {
          dlUrl_ = other.dlUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pengcui.protoBuf.bufClass.Buf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pengcui.protoBuf.bufClass.Buf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int operateType_ ;
      /**
       * <code>optional int32 operateType = 1;</code>
       */
      public int getOperateType() {
        return operateType_;
      }
      /**
       * <code>optional int32 operateType = 1;</code>
       */
      public Builder setOperateType(int value) {
        
        operateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 operateType = 1;</code>
       */
      public Builder clearOperateType() {
        
        operateType_ = 0;
        onChanged();
        return this;
      }

      private boolean isDel_ ;
      /**
       * <pre>
       *0.输入法
       * </pre>
       *
       * <code>optional bool isDel = 22;</code>
       */
      public boolean getIsDel() {
        return isDel_;
      }
      /**
       * <pre>
       *0.输入法
       * </pre>
       *
       * <code>optional bool isDel = 22;</code>
       */
      public Builder setIsDel(boolean value) {
        
        isDel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0.输入法
       * </pre>
       *
       * <code>optional bool isDel = 22;</code>
       */
      public Builder clearIsDel() {
        
        isDel_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object inputText_ = "";
      /**
       * <code>optional string InputText = 2;</code>
       */
      public java.lang.String getInputText() {
        java.lang.Object ref = inputText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          inputText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string InputText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInputTextBytes() {
        java.lang.Object ref = inputText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inputText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string InputText = 2;</code>
       */
      public Builder setInputText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        inputText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string InputText = 2;</code>
       */
      public Builder clearInputText() {
        
        inputText_ = getDefaultInstance().getInputText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string InputText = 2;</code>
       */
      public Builder setInputTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        inputText_ = value;
        onChanged();
        return this;
      }

      private int gpsStart_ ;
      /**
       * <pre>
       *1.gps
       * </pre>
       *
       * <code>optional int32 gpsStart = 3;</code>
       */
      public int getGpsStart() {
        return gpsStart_;
      }
      /**
       * <pre>
       *1.gps
       * </pre>
       *
       * <code>optional int32 gpsStart = 3;</code>
       */
      public Builder setGpsStart(int value) {
        
        gpsStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1.gps
       * </pre>
       *
       * <code>optional int32 gpsStart = 3;</code>
       */
      public Builder clearGpsStart() {
        
        gpsStart_ = 0;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>optional double longitude = 4;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>optional double latitude = 5;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 5;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 5;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>optional double altitude = 6;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>optional double altitude = 6;</code>
       */
      public Builder setAltitude(double value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double altitude = 6;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private long delay_ ;
      /**
       * <code>optional int64 delay = 15;</code>
       */
      public long getDelay() {
        return delay_;
      }
      /**
       * <code>optional int64 delay = 15;</code>
       */
      public Builder setDelay(long value) {
        
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 delay = 15;</code>
       */
      public Builder clearDelay() {
        
        delay_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       *3.打开网页
       * </pre>
       *
       * <code>optional string url = 9;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *3.打开网页
       * </pre>
       *
       * <code>optional string url = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *3.打开网页
       * </pre>
       *
       * <code>optional string url = 9;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *3.打开网页
       * </pre>
       *
       * <code>optional string url = 9;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *3.打开网页
       * </pre>
       *
       * <code>optional string url = 9;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int keyCode_ ;
      /**
       * <pre>
       *4.物理按键
       * </pre>
       *
       * <code>optional int32 keyCode = 10;</code>
       */
      public int getKeyCode() {
        return keyCode_;
      }
      /**
       * <pre>
       *4.物理按键
       * </pre>
       *
       * <code>optional int32 keyCode = 10;</code>
       */
      public Builder setKeyCode(int value) {
        
        keyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *4.物理按键
       * </pre>
       *
       * <code>optional int32 keyCode = 10;</code>
       */
      public Builder clearKeyCode() {
        
        keyCode_ = 0;
        onChanged();
        return this;
      }

      private int findOf_ ;
      /**
       * <pre>
       *5.查找元素位置
       * </pre>
       *
       * <code>optional int32 findOf = 11;</code>
       */
      public int getFindOf() {
        return findOf_;
      }
      /**
       * <pre>
       *5.查找元素位置
       * </pre>
       *
       * <code>optional int32 findOf = 11;</code>
       */
      public Builder setFindOf(int value) {
        
        findOf_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *5.查找元素位置
       * </pre>
       *
       * <code>optional int32 findOf = 11;</code>
       */
      public Builder clearFindOf() {
        
        findOf_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object findStr_ = "";
      /**
       * <code>optional string findStr = 12;</code>
       */
      public java.lang.String getFindStr() {
        java.lang.Object ref = findStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          findStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string findStr = 12;</code>
       */
      public com.google.protobuf.ByteString
          getFindStrBytes() {
        java.lang.Object ref = findStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          findStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string findStr = 12;</code>
       */
      public Builder setFindStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        findStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string findStr = 12;</code>
       */
      public Builder clearFindStr() {
        
        findStr_ = getDefaultInstance().getFindStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string findStr = 12;</code>
       */
      public Builder setFindStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        findStr_ = value;
        onChanged();
        return this;
      }

      private boolean isChild_ ;
      /**
       * <code>optional bool isChild = 24;</code>
       */
      public boolean getIsChild() {
        return isChild_;
      }
      /**
       * <code>optional bool isChild = 24;</code>
       */
      public Builder setIsChild(boolean value) {
        
        isChild_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isChild = 24;</code>
       */
      public Builder clearIsChild() {
        
        isChild_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object childStr_ = "";
      /**
       * <code>optional string childStr = 25;</code>
       */
      public java.lang.String getChildStr() {
        java.lang.Object ref = childStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          childStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string childStr = 25;</code>
       */
      public com.google.protobuf.ByteString
          getChildStrBytes() {
        java.lang.Object ref = childStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          childStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string childStr = 25;</code>
       */
      public Builder setChildStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        childStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string childStr = 25;</code>
       */
      public Builder clearChildStr() {
        
        childStr_ = getDefaultInstance().getChildStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string childStr = 25;</code>
       */
      public Builder setChildStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        childStr_ = value;
        onChanged();
        return this;
      }

      private int childLayer_ ;
      /**
       * <code>optional int32 childLayer = 26;</code>
       */
      public int getChildLayer() {
        return childLayer_;
      }
      /**
       * <code>optional int32 childLayer = 26;</code>
       */
      public Builder setChildLayer(int value) {
        
        childLayer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 childLayer = 26;</code>
       */
      public Builder clearChildLayer() {
        
        childLayer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cmdStr_ = "";
      /**
       * <pre>
       *6.执行命令 
       * </pre>
       *
       * <code>optional string cmdStr = 13;</code>
       */
      public java.lang.String getCmdStr() {
        java.lang.Object ref = cmdStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmdStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *6.执行命令 
       * </pre>
       *
       * <code>optional string cmdStr = 13;</code>
       */
      public com.google.protobuf.ByteString
          getCmdStrBytes() {
        java.lang.Object ref = cmdStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *6.执行命令 
       * </pre>
       *
       * <code>optional string cmdStr = 13;</code>
       */
      public Builder setCmdStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmdStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *6.执行命令 
       * </pre>
       *
       * <code>optional string cmdStr = 13;</code>
       */
      public Builder clearCmdStr() {
        
        cmdStr_ = getDefaultInstance().getCmdStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *6.执行命令 
       * </pre>
       *
       * <code>optional string cmdStr = 13;</code>
       */
      public Builder setCmdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmdStr_ = value;
        onChanged();
        return this;
      }

      private boolean isRoot_ ;
      /**
       * <code>optional bool isRoot = 14;</code>
       */
      public boolean getIsRoot() {
        return isRoot_;
      }
      /**
       * <code>optional bool isRoot = 14;</code>
       */
      public Builder setIsRoot(boolean value) {
        
        isRoot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isRoot = 14;</code>
       */
      public Builder clearIsRoot() {
        
        isRoot_ = false;
        onChanged();
        return this;
      }

      private int contactType_ ;
      /**
       * <pre>
       *7.添加联系人
       * </pre>
       *
       * <code>optional int32 contactType = 23;</code>
       */
      public int getContactType() {
        return contactType_;
      }
      /**
       * <pre>
       *7.添加联系人
       * </pre>
       *
       * <code>optional int32 contactType = 23;</code>
       */
      public Builder setContactType(int value) {
        
        contactType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *7.添加联系人
       * </pre>
       *
       * <code>optional int32 contactType = 23;</code>
       */
      public Builder clearContactType() {
        
        contactType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object contactName_ = "";
      /**
       * <code>optional string contactName = 16;</code>
       */
      public java.lang.String getContactName() {
        java.lang.Object ref = contactName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public com.google.protobuf.ByteString
          getContactNameBytes() {
        java.lang.Object ref = contactName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder setContactName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder clearContactName() {
        
        contactName_ = getDefaultInstance().getContactName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder setContactNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contactNum_ = "";
      /**
       * <code>optional string contactNum = 17;</code>
       */
      public java.lang.String getContactNum() {
        java.lang.Object ref = contactNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contactNum = 17;</code>
       */
      public com.google.protobuf.ByteString
          getContactNumBytes() {
        java.lang.Object ref = contactNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contactNum = 17;</code>
       */
      public Builder setContactNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactNum = 17;</code>
       */
      public Builder clearContactNum() {
        
        contactNum_ = getDefaultInstance().getContactNum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactNum = 17;</code>
       */
      public Builder setContactNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactNum_ = value;
        onChanged();
        return this;
      }

      private int contactCount_ ;
      /**
       * <code>optional int32 contactCount = 19;</code>
       */
      public int getContactCount() {
        return contactCount_;
      }
      /**
       * <code>optional int32 contactCount = 19;</code>
       */
      public Builder setContactCount(int value) {
        
        contactCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contactCount = 19;</code>
       */
      public Builder clearContactCount() {
        
        contactCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       *9.上传文件
       * </pre>
       *
       * <code>optional string fileName = 20;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *9.上传文件
       * </pre>
       *
       * <code>optional string fileName = 20;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *9.上传文件
       * </pre>
       *
       * <code>optional string fileName = 20;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *9.上传文件
       * </pre>
       *
       * <code>optional string fileName = 20;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *9.上传文件
       * </pre>
       *
       * <code>optional string fileName = 20;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int fileLen_ ;
      /**
       * <code>optional int32 fileLen = 21;</code>
       */
      public int getFileLen() {
        return fileLen_;
      }
      /**
       * <code>optional int32 fileLen = 21;</code>
       */
      public Builder setFileLen(int value) {
        
        fileLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fileLen = 21;</code>
       */
      public Builder clearFileLen() {
        
        fileLen_ = 0;
        onChanged();
        return this;
      }

      private boolean wxRun_ ;
      /**
       * <pre>
       *10.设置微信自动回复的开始或暂停，默认暂停
       * </pre>
       *
       * <code>optional bool wxRun = 29;</code>
       */
      public boolean getWxRun() {
        return wxRun_;
      }
      /**
       * <pre>
       *10.设置微信自动回复的开始或暂停，默认暂停
       * </pre>
       *
       * <code>optional bool wxRun = 29;</code>
       */
      public Builder setWxRun(boolean value) {
        
        wxRun_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *10.设置微信自动回复的开始或暂停，默认暂停
       * </pre>
       *
       * <code>optional bool wxRun = 29;</code>
       */
      public Builder clearWxRun() {
        
        wxRun_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object gText_ = "";
      /**
       * <pre>
       *12.设置屏幕广告
       * </pre>
       *
       * <code>optional string gText = 27;</code>
       */
      public java.lang.String getGText() {
        java.lang.Object ref = gText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *12.设置屏幕广告
       * </pre>
       *
       * <code>optional string gText = 27;</code>
       */
      public com.google.protobuf.ByteString
          getGTextBytes() {
        java.lang.Object ref = gText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *12.设置屏幕广告
       * </pre>
       *
       * <code>optional string gText = 27;</code>
       */
      public Builder setGText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gText_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *12.设置屏幕广告
       * </pre>
       *
       * <code>optional string gText = 27;</code>
       */
      public Builder clearGText() {
        
        gText_ = getDefaultInstance().getGText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *12.设置屏幕广告
       * </pre>
       *
       * <code>optional string gText = 27;</code>
       */
      public Builder setGTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gText_ = value;
        onChanged();
        return this;
      }

      private boolean gView_ ;
      /**
       * <code>optional bool gView = 28;</code>
       */
      public boolean getGView() {
        return gView_;
      }
      /**
       * <code>optional bool gView = 28;</code>
       */
      public Builder setGView(boolean value) {
        
        gView_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool gView = 28;</code>
       */
      public Builder clearGView() {
        
        gView_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object robotApiKey_ = "";
      /**
       * <pre>
       *15.设置聊天机器人api的key和userId
       * </pre>
       *
       * <code>optional string robotApiKey = 30;</code>
       */
      public java.lang.String getRobotApiKey() {
        java.lang.Object ref = robotApiKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          robotApiKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *15.设置聊天机器人api的key和userId
       * </pre>
       *
       * <code>optional string robotApiKey = 30;</code>
       */
      public com.google.protobuf.ByteString
          getRobotApiKeyBytes() {
        java.lang.Object ref = robotApiKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          robotApiKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *15.设置聊天机器人api的key和userId
       * </pre>
       *
       * <code>optional string robotApiKey = 30;</code>
       */
      public Builder setRobotApiKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        robotApiKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *15.设置聊天机器人api的key和userId
       * </pre>
       *
       * <code>optional string robotApiKey = 30;</code>
       */
      public Builder clearRobotApiKey() {
        
        robotApiKey_ = getDefaultInstance().getRobotApiKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *15.设置聊天机器人api的key和userId
       * </pre>
       *
       * <code>optional string robotApiKey = 30;</code>
       */
      public Builder setRobotApiKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        robotApiKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dlUrl_ = "";
      /**
       * <pre>
       *17.从手机给电脑下载文件
       * </pre>
       *
       * <code>optional string dlUrl = 31;</code>
       */
      public java.lang.String getDlUrl() {
        java.lang.Object ref = dlUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dlUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *17.从手机给电脑下载文件
       * </pre>
       *
       * <code>optional string dlUrl = 31;</code>
       */
      public com.google.protobuf.ByteString
          getDlUrlBytes() {
        java.lang.Object ref = dlUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dlUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *17.从手机给电脑下载文件
       * </pre>
       *
       * <code>optional string dlUrl = 31;</code>
       */
      public Builder setDlUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dlUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *17.从手机给电脑下载文件
       * </pre>
       *
       * <code>optional string dlUrl = 31;</code>
       */
      public Builder clearDlUrl() {
        
        dlUrl_ = getDefaultInstance().getDlUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *17.从手机给电脑下载文件
       * </pre>
       *
       * <code>optional string dlUrl = 31;</code>
       */
      public Builder setDlUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dlUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pengcui.protoBuf.Buf)
    }

    // @@protoc_insertion_point(class_scope:pengcui.protoBuf.Buf)
    private static final pengcui.protoBuf.bufClass.Buf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pengcui.protoBuf.bufClass.Buf();
    }

    public static pengcui.protoBuf.bufClass.Buf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Buf>
        PARSER = new com.google.protobuf.AbstractParser<Buf>() {
      public Buf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Buf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Buf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Buf> getParserForType() {
      return PARSER;
    }

    public pengcui.protoBuf.bufClass.Buf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pengcui_protoBuf_Buf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pengcui_protoBuf_Buf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020main_proto.proto\022\020pengcui.protoBuf\"\362\003\n" +
      "\003Buf\022\023\n\013operateType\030\001 \001(\005\022\r\n\005isDel\030\026 \001(\010" +
      "\022\021\n\tInputText\030\002 \001(\t\022\020\n\010gpsStart\030\003 \001(\005\022\021\n" +
      "\tlongitude\030\004 \001(\001\022\020\n\010latitude\030\005 \001(\001\022\020\n\010al" +
      "titude\030\006 \001(\001\022\r\n\005delay\030\017 \001(\003\022\013\n\003url\030\t \001(\t" +
      "\022\017\n\007keyCode\030\n \001(\005\022\016\n\006findOf\030\013 \001(\005\022\017\n\007fin" +
      "dStr\030\014 \001(\t\022\017\n\007isChild\030\030 \001(\010\022\020\n\010childStr\030" +
      "\031 \001(\t\022\022\n\nchildLayer\030\032 \001(\005\022\016\n\006cmdStr\030\r \001(" +
      "\t\022\016\n\006isRoot\030\016 \001(\010\022\023\n\013contactType\030\027 \001(\005\022\023" +
      "\n\013contactName\030\020 \001(\t\022\022\n\ncontactNum\030\021 \001(\t\022",
      "\024\n\014contactCount\030\023 \001(\005\022\020\n\010fileName\030\024 \001(\t\022" +
      "\017\n\007fileLen\030\025 \001(\005\022\r\n\005wxRun\030\035 \001(\010\022\r\n\005gText" +
      "\030\033 \001(\t\022\r\n\005gView\030\034 \001(\010\022\023\n\013robotApiKey\030\036 \001" +
      "(\t\022\r\n\005dlUrl\030\037 \001(\tB\034\n\020pengcui.protoBufB\010b" +
      "ufClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pengcui_protoBuf_Buf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pengcui_protoBuf_Buf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pengcui_protoBuf_Buf_descriptor,
        new java.lang.String[] { "OperateType", "IsDel", "InputText", "GpsStart", "Longitude", "Latitude", "Altitude", "Delay", "Url", "KeyCode", "FindOf", "FindStr", "IsChild", "ChildStr", "ChildLayer", "CmdStr", "IsRoot", "ContactType", "ContactName", "ContactNum", "ContactCount", "FileName", "FileLen", "WxRun", "GText", "GView", "RobotApiKey", "DlUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
